# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PermissionDelegateExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for PermissionDelegateExample
  pod 'SwrveSDK', '6.7.0'
end
